### ISSUE TITLE
Offset from left

### ISSUE THREAD

**Issue by ozanmuyes** [wes-goulet/side-drawer#98]
Is it possible to give it some offset from left (if it's **not** `right`ed) _or offset from right (if `<side-drawer right>`)_? I saw the [applicable CSS properties](https://github.com/wes-goulet/side-drawer?tab=readme-ov-file#styling), but they are not useful for what I want to achieve.

**Comment by ozanmuyes** [comment]
This is to fulfill my use-case but I think it's a common use-case to have so-called collapsed drawers / sidebars when closed it won't hide away but _collapses_ to a minified version of the drawer / sidebar.

**Comment by wes-goulet** [comment]
@ozanmuyes This should be possible today, the underlying `dialog` is exposed as a part, so something like the following should work:

```css
side-drawer::part(dialog) {
  left: 80px;
}
```

Will that work for your use case?  I'd rather consumers leverage the `dialog` part over adding more CSS properties (and expanding the component's API surface).

**Comment by ozanmuyes** [comment]
I wasn't aware of `::part()`, thanks!
